#!/usr/bin/env python3
"""Add assessment test and multi-select questions from the CompTIA Security+ Study Guide."""

import json
import sqlite3
from pathlib import Path

BASE_DIR = Path(__file__).parent
DB_PATH = BASE_DIR / "progress.db"
COURSE_ID = "secplus"

QUESTIONS = [
    {"c": 10, "q": "To avoid disruption of the work process for office workers", "o": ["To prevent security breaches due to malicious patches and updates", "To avoid issues with problematic patches and updates", "All of the above", "Which of the following is the least volatile according to the forensic order of volatility?"], "a": 2, "exp": "The most common reason to disable automatic patching is to avoid issues with problematic or flawed patches and updates. In most environments the need to patch regularly is accepted and handled for office workers without causing significant disruption. That concern would be different if the systems being patched were part of an industrial process or factory production environment. Malicious patches from legitimate sources such as an automatic update repository are exceptionally rare and are not a common concern or driver of this behavior. For more information, see Chapter 11."},
    {"c": 14, "q": "The system's routing table", "o": ["Logs", "Temp files", "CPU registers", "Ed wants to trick a user into connecting to his evil twin access point (AP). What type of attack should he conduct to increase his chances of the user connecting to it?"], "a": 1, "exp": "Logs, along with any file that is stored on disk without the intention of being frequently overwritten, are the least volatile item listed. In order from most volatile to least from the answers here, you could list these as CPU registers, the system's routing table, temp files, and logs. For more information, see Chapter 15."},
    {"c": 11, "q": "A disassociation attack", "o": ["An application denial-of-service attack", "A known plain-text attack", "A network denial-of-service attack", "What term is used to describe wireless site surveys that show the relative power of access points on a diagram of the building or facility?"], "a": 0, "exp": "If Ed can cause his target to disassociate from the access point they are currently connected to, he can use a higher transmission power or closer access point to appear higher in the list of access points. If he is successful at fooling the user or system into connecting to his AP, he can then conduct on-path attacks or attempt other exploits. Denial-of-service attacks are unlikely to cause a system to associate with another AP, and a known plain-text attack is a type of cryptographic attack and is not useful for this type of attempt. For more information, see Chapter 12."},
    {"c": 12, "q": "Signal surveys", "o": ["db maps", "AP topologies", "Heatmaps", "What hardware device is used to create the hardware root of trust for modern desktops and laptops?"], "a": 3, "exp": "Site surveys that show relative power on a map or diagram are called heatmaps. They can help show where access points provide a strong signal, and where multiple APs may be competing with each other due to channel overlap or other issues. They can also help identify dead zones where signal does not reach. Signal surveys, db maps, and AP topologies were made up for this question. For more information, see Chapter 13."},
    {"c": 10, "q": "System memory", "o": ["A HSM", "The CPU", "The TPM", "Angela wants to prevent users in her organization from changing their passwords repeatedly after they have been changed so that they cannot reuse their current password. What two password security settings does she need to implement to make this occur?"], "a": 3, "exp": "A hardware root of trust provides a unique element that means that a board or device cannot be replicated. A Trusted Platform Module (TPM) is commonly used to provide the hardware root of trust. CPUs and system memory are not unique in this way for common desktops and laptops, and a hardware security module (HSM) is used to create, manage, and store cryptographic certificates as well as perform and offload cryptographic operations. For more information, see Chapter 11."},
    {"c": 7, "q": "Set a password history and a minimum password age.", "o": ["Set a password history and a complexity setting.", "Set a password minimum and maximum age.", "Set password complexity and maximum age.", "Chris wants to establish a backup site that is fully ready to take over for full operations for his organization at any time. What type of site should he set up?"], "a": 0, "exp": "Angela needs to retain a password history and set a minimum password age so that users cannot simply reset their password until they have changed the password enough times to bypass the history. For more information, see Chapter 8."},
    {"c": 8, "q": "A cold site", "o": ["A clone site", "A hot site", "A ready site", "Which of the following is not a common constraint of embedded and specialized systems?"], "a": 2, "exp": "Hot sites are ready to take over operations in real time. Cold sites are typically simply ready buildings with basic infrastructure in place to set up a site. Clone sites and ready sites are not typical terms used in the industry. For more information, see Chapter 9."},
    {"c": 10, "q": "Computational power", "o": ["Overly complex firewall settings", "Lack of network connectivity", "Inability to patch", "Gary is reviewing his system's SSH logs and sees logins for the user named “Gary” with passwords like password1, password2 … PassworD. What type of attack has Gary discovered?"], "a": 1, "exp": "Embedded and specialized systems tend to have lower-power CPUs, less memory, less storage, and often may not be able to handle CPU-intensive tasks like cryptographic algorithms or built-in security tools. Thus, having a firewall is relatively unlikely, particularly if there isn't network connectivity built in or the device is expected to be deployed to a secure network. For more information, see Chapter 11."},
    {"c": 3, "q": "A dictionary attack", "o": ["A rainbow table attack", "A pass-the-hash attack", "A password spraying attack", "Kathleen wants to set up a system that allows access into a high-security zone from a low-security zone. What type of solution should she configure?"], "a": 0, "exp": "A dictionary attack will use a set of likely passwords along with common variants of those passwords to try to break into an account. Repeated logins for a single user ID with iterations of various passwords is likely a dictionary account. A rainbow table is used to match a hashed password with the password that was hashed to that value. A pass-the-hash attack provides a captured authentication hash to try to act like an authorized user. A password spraying attack uses a known password (often from a breach) for many different sites to try to log in to them. For more information, see Chapter 4."},
    {"c": 11, "q": "VDI", "o": ["A container", "A screened subnet", "A jump server", "Derek's organization is worried about a disgruntled employee publishing sensitive business information. What type of threat should Derek work to protect against?"], "a": 3, "exp": "Jump servers are systems that are used to provide a presence and access path in a different security zone. VDI is a virtual desktop infrastructure and is used to provide controlled virtual systems for productivity and application presentation among other uses. A container is a way to provide a scalable, predictable application environment without having a full underlying virtual system, and a screened subnet is a secured zone exposed to a lower trust level area or population. For more information, see Chapter 12."},
    {"c": 1, "q": "Shoulder surfing", "o": ["Social engineering", "Insider threats", "Phishing", "Jeff is concerned about the effects that a ransomware attack might have on his organization and is designing a backup methodology that would allow the organization to quickly restore data after such an attack. What type of control is Jeff implementing?"], "a": 2, "exp": "Derek's organization is worried about insider threats, or threats that are created by employees and others who are part of the organization or are otherwise trusted by the organization. Social engineering involves deceiving people to achieve an attacker's goals. Phishing attempts to acquire personal information through social engineering and other techniques, and shoulder surfing is a technique where malicious actors watch over someone's shoulder to acquire information like passwords or credit card numbers. For more information, see Chapter 2."},
    {"c": 0, "q": "Corrective", "o": ["Preventive", "Detective", "Deterrent", "Samantha is investigating a cybersecurity incident where an internal user used his computer to participate in a denial-of-service attack against a third party. What type of policy was most likely violated?"], "a": 0, "exp": "Corrective controls remediate security issues that have already occurred. Restoring backups after a ransomware attack is an example of a corrective control. Preventative controls attempt to stop future issues. Detective controls focus on detecting issues and events, and deterrent controls attempt to deter actions. For more information, see Chapter 1."},
    {"c": 15, "q": "BPA", "o": ["SLA", "AUP", "MOU", "Jean recently completed the user acceptance testing process and is getting her code ready to deploy. What environment should house her code before it is released for use?"], "a": 2, "exp": "This activity is almost certainly a violation of the organization's acceptable use policy (AUP), which should contain provisions describing appropriate use of networks and computing resources belonging to the organization. BPA is not a common term in this context. Service level agreements (SLAs) determine an agreed upon level of service, and MOUs, or memorandums of understanding are used to document agreements between organizations. See Chapter 16 for more information."},
    {"c": 5, "q": "Test", "o": ["Production", "Development", "Staging", "Rob has created a document that describes how staff in his organization can use organizationally owned devices, including if and when personal use is allowed. What type of policy has Rob created?"], "a": 3, "exp": "The staging environment is a transition environment for code that has successfully cleared testing and is waiting to be deployed into production. This is where the code should reside before it is released for use. The development environment is where developers work on the code prior to preparing it for deployment. The test environment is where the software or systems can be tested without impacting the production environment. The production environment is the live system. Software, patches, and other changes that have been tested and approved move to production. For more information, see Chapter 6."},
    {"c": 15, "q": "A change management policy", "o": ["An acceptable use policy", "An access control policy", "A playbook", "Oren obtained a certificate for his domain covering *.acmewidgets.net. Which one of the following domains would not be covered by this certificate?"], "a": 1, "exp": "Acceptable use policies define how organizational systems, devices, and services can and should be used. Change management policies determine how an organization handles change and change control. Access control documentation is typically handled as a standard, and playbooks describe how perform specific duties or processes."},
    {"c": 6, "q": "www.acmewidgets.net", "o": ["acmewidgets.net", "test.mail.acmewidgets.net", "mobile.acmewidgets.net", "Richard is sending a message to Grace and would like to apply a digital signature to the message before sending it. What key should he use to create the digital signature?"], "a": 2, "exp": "Wildcard certificates protect the listed domain as well as all first-level subdomains. test.mail.acmewidgets.net is a second-level subdomain of acmewidgets.net and would not be covered by this certificate. For more information, see Chapter 7."},
    {"c": 6, "q": "Richard's private key", "o": ["Richard's public key", "Grace's private key", "Grace's public key", "Stephanie is reviewing a customer transaction database and comes across the data table shown here. What data minimization technique has most likely been used to obscure the credit card information in this table?"], "a": 0, "exp": "The sender of a message may digitally sign the message by encrypting a message digest with the sender's own private key. For more information, see Chapter 7."},
    {"c": 0, "q": "Destruction", "o": ["Masking", "Hashing", "Tokenization", "Andrew is working with his financial team to purchase a cybersecurity insurance policy to cover the financial impact of a data breach. What type of risk management strategy is he using?"], "a": 2, "exp": "This data most closely resembles hashed data, as the fields are all the same length and appear to contain meaningless but unique data. If the field was tokenized, it would be more likely to contain a sequential number or other recognizable identifier. If the field was masked, it would contain asterisks or other placeholder characters. For more information, see Chapter 1."},
    {"c": 16, "q": "Risk avoidance", "o": ["Risk transference", "Risk acceptance", "Risk mitigation", "Shelly is writing a document that describes the steps that incident response teams will follow upon first notice of a potential incident. What type of document is she creating?"], "a": 1, "exp": "Purchasing insurance is the most common example of risk transference—shifting liability to a third party. Avoidance involves efforts to prevent the risk from occurring, acceptance is just that—formally accepting that the risk may occur, and mitigation attempts to limit the impact of the risk. For more information, see Chapter 17."},
    {"c": 15, "q": "Guideline", "o": ["Standard", "Procedure", "Policy", "Answers to Assessment Test"], "a": 2, "exp": "Procedures provide checklist-style sets of step-by-step instructions guiding how employees should react in a given circumstance. Procedures commonly guide the early stages of incident response. Standards define how policies should be implemented. Guidelines are voluntary, whereas policies are mandatory. For more information, see Chapter 16."},
    {"c": 1, "q": "Edward Snowden was a government contractor who disclosed sensitive government documents to journalists to uncover what he believed were unethical activities. Which of the following terms best describe Snowden's activities? (Choose two.)", "o": ["Insider", "State actor", "Hacktivist", "APT"], "a": 0, "exp": "Correct answers: A (Insider) and C (Hacktivist). As a government contractor, Snowden had authorized access to classified information and exploited this access to make an unauthorized disclosure. This makes him an insider. He did so with political motivations, making him a hacktivist as well."},
]

def migrate(conn):
    c = conn.cursor()
    
    last_order = c.execute(
        "SELECT COALESCE(MAX(sort_order), 0) FROM quiz_questions WHERE course_id = ?",
        (COURSE_ID,),
    ).fetchone()[0]
    
    for qi, q in enumerate(QUESTIONS):
        c.execute(
            "INSERT INTO quiz_questions (course_id, chapter_idx, question_text, options_json, correct_idx, explanation, sort_order) VALUES (?,?,?,?,?,?,?)",
            (COURSE_ID, q["c"], q["q"], json.dumps(q["o"]), q["a"], q["exp"], last_order + qi + 1),
        )
    
    conn.commit()
    print(f"Inserted {len(QUESTIONS)} additional questions into secplus course.")

if __name__ == "__main__":
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("PRAGMA journal_mode=WAL")
    migrate(conn)
    conn.close()
    print("Migration complete")
